# Generated by Django 5.2.8 on 2025-11-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_matter_activity_matter_assignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='status',
        ),
        migrations.AddField(
            model_name='matter',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='state',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved')], default='IN_PROGRESS', max_length=50),
        ),
        migrations.AddField(
            model_name='matter',
            name='type',
            field=models.CharField(choices=[('CIVIL', 'Civil'), ('CRIMINAL', 'Criminal'), ('FAMILY_LAW', 'Family Law'), ('APPEAL', 'Appeal'), ('PROBATE', 'Probate'), ('SMALL_CLAIMS', 'Small Claims')], default='CIVIL', max_length=50),
        ),
        migrations.AlterField(
            model_name='matter',
            name='assignee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
