# Generated by Django 5.2.8 on 2025-11-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_matter_status_matter_client_matter_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matter',
            old_name='activity',
            new_name='title',
        ),
    ]
