# Generated by Django 5.2.8 on 2025-11-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_activity_matter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='work_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
