# Generated by Django 5.2.8 on 2025-11-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_matter_description_matter_work_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matter',
            old_name='description',
            new_name='shortDescription',
        ),
    ]
