# Generated by Django 5.2.8 on 2025-12-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_matter_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='type',
            field=models.CharField(choices=[('CIVIL', 'Civil'), ('CRIMINAL', 'Criminal'), ('FAMILY_LAW', 'Family Law'), ('APPEAL', 'Appeal'), ('PROBATE', 'Probate'), ('SMALL_CLAIMS', 'Small Claims')], max_length=50),
        ),
    ]
