# Generated by Django 5.2.8 on 2025-12-01 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def clear_assignee_data(apps, schema_editor):
    # Get the model snapshot used for this migration point
    Matter = apps.get_model('api', 'Matter') # Replace 'api' with your app name
    
    # Update all records, setting the old string value to None (NULL)
    Matter.objects.all().update(assignee=None)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_matter_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matter',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),

        migrations.RunPython(clear_assignee_data, migrations.RunPython.noop),
    ]
