# Generated by Django 6.0 on 2025-12-05 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_matter_approver_alter_matter_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resdb_tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.matter')),
            ],
        ),
        migrations.CreateModel(
            name='MatterTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_in_progress_id', models.CharField(max_length=100)),
                ('txn_pending_approval_id', models.CharField(max_length=100)),
                ('txn_approved_id', models.CharField(max_length=100)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matter')),
            ],
        ),
    ]
